-- Soil Field Monitor — Supabase schema
-- Run this once in the Supabase SQL editor for your project.

create table if not exists readings (
  id bigint generated by default as identity primary key,
  soil_moisture numeric not null,   -- percent, 0-100
  temperature numeric not null,     -- degrees Celsius
  created_at timestamptz not null default now()
);

alter table readings enable row level security;

-- The ESP32 uses the anon key to insert new readings
create policy "Allow insert from device"
  on readings for insert
  to anon
  with check (true);

-- The dashboard uses the anon key to read readings
create policy "Allow public read"
  on readings for select
  to anon
  using (true);

-- Optional housekeeping: keep only the last 30 days of readings.
-- Run manually now and then, or schedule with pg_cron if your project has it enabled:
-- delete from readings where created_at < now() - interval '30 days';


-- ------------------------------------------------------------
-- AUTOMATIC IRRIGATION
-- The ESP32 writes the current pump state and irrigation events.
-- The dashboard can read these rows for pump status/history.
-- ------------------------------------------------------------
alter table readings add column if not exists device_id text default 'ESP32-Field-01';

create table if not exists irrigation_events (
  id bigint generated by default as identity primary key,
  device_id text not null default 'ESP32-Field-01',
  moisture_before numeric,
  moisture_after numeric,
  duration_seconds integer not null,
  trigger text not null, -- 'automatic' or 'manual'
  created_at timestamptz not null default now()
);

alter table irrigation_events enable row level security;

create policy "Allow irrigation insert from device"
  on irrigation_events for insert
  to anon
  with check (true);

create policy "Allow irrigation public read"
  on irrigation_events for select
  to anon
  using (true);


-- ------------------------------------------------------------
-- PUMP COMMANDS
-- Dashboard inserts a command; ESP32 polls and executes the latest
-- unprocessed command for its device.
-- ------------------------------------------------------------
create table if not exists pump_commands (
  id bigint generated by default as identity primary key,
  device_id text not null default 'ESP32-Field-01',
  command text not null check (command in ('ON','OFF','AUTO')),
  processed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table pump_commands enable row level security;

create policy "Allow pump command insert"
  on pump_commands for insert to anon with check (true);

create policy "Allow pump command read"
  on pump_commands for select to anon using (true);

create policy "Allow pump command update"
  on pump_commands for update to anon using (true) with check (true);
