-- Soil Field Monitor — Supabase schema
-- Run this once in the Supabase SQL editor for your project.

create table if not exists readings (
  id bigint generated by default as identity primary key,
  soil_moisture numeric not null,   -- percent, 0-100
  temperature numeric not null,     -- degrees Celsius
  created_at timestamptz not null default now()
);

alter table readings enable row level security;

-- The ESP32 uses the anon key to insert new readings
create policy "Allow insert from device"
  on readings for insert
  to anon
  with check (true);

-- The dashboard uses the anon key to read readings
create policy "Allow public read"
  on readings for select
  to anon
  using (true);

-- Optional housekeeping: keep only the last 30 days of readings.
-- Run manually now and then, or schedule with pg_cron if your project has it enabled:
-- delete from readings where created_at < now() - interval '30 days';
